# ===================================================================
# 开发工具时时默认的配置
#
# 所有相对路径以本项目根目录为准
# ===================================================================

stub-api:
  process:
    generators:
      - com.github.kamicloud.stub.core.generators.OpenAPIGenerator
      - com.github.kamicloud.stub.core.generators.PostmanGenerator
      - com.github.kamicloud.stub.core.generators.TestCaseGenerator

      - com.github.kamicloud.stub.laravel.LaravelGenerator
      - com.github.kamicloud.stub.laravel.LaravelDocGenerator
#      - com.kamicloud.stub.laravel.LaravelAutoTestGenerator

    defaults:
      - laravel
      - laravel-doc
      - postman
      - testcases
      - openapi
    laravel-auto-test:
      - laravel-auto-test
    client:
      - nodejs-client
  env: dev
  api-prefix: api
  template-path: ./src/main/java

  test-host: http://localhost

  generators:
    force-suffix: .example

    openapi:
      path: ./output
    postman:
      path: ./output
    testcases:
      path: ./output/testcases

    laravel:
      path: ./output/laravel

      bo-suffix: BO
      bo-folder: BOs
      dto-suffix: DTO
      dto-folder: DTOs
      service-suffix: Service
      service-folder: Services
      value-helper-namespace: 'Kamicloud\StubApi\Concerns\ValueHelper'
      base-dto-namespace: 'Kamicloud\StubApi\DTOs\DTO'
      base-message-namespace: 'Kamicloud\StubApi\Http\Messages\Message'
      base-enum-namespace: 'Kamicloud\StubApi\BOs\Enum'
      base-exception-namespace: 'Kamicloud\StubApi\Exceptions\BaseException'
    laravel-doc:
      path: ./output/larecipe
      http-prefix: docs
    laravel-auto-test:
      path: ./output/tests
      force-replace: false
      testcases-path: ./output/testcases


    nodejs-client:
      output: ./output/nodejs-client
    java-client:
      path: ./output/java-client
      classpath:

spring:
  profiles:
    active: dev
  thymeleaf:
    mode: TEXT
    suffix: .stub
    encoding: UTF-8
    prefix: classpath:stubs/
