# ===================================================================
# Spring Boot configuration for the "dev" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

logging:
  level:
     ROOT: DEBUG
     io.github.jhipster: DEBUG
     com.zhh.blog: DEBUG

generator:
  template-path: ./src/main/java
  laravel-path: ./output/laravel
  auto-test-path: ./output/tests
  doc-path: ./output/docs
  postman-path: ./output
  testcases-path: ./output/testcases
  test-host: http://localhost

#spring:
#    profiles:
#        active: dev
