# ===================================================================
# 开发工具时时默认的配置
#
# 所有相对路径以本项目根目录为准
# ===================================================================

generator:
  env: dev
  api-prefix: api
  template-path: ./src/main/java
  laravel-path: ./src/output/laravel
  auto-test-path: ./src/output/tests
  auto-test-force-replace: false
  doc-path: ./src/output/larecipe
  doc-http-prefix: docs
  postman-path: ./src/output
  testcases-path: ./src/output/testcases
  test-host: http://localhost
  java-client-path: ./src/output/java-client
  java-client-classpath:
