# ===================================================================
# 开发工具时时默认的配置
#
# 所有相对路径以本项目根目录为准
# ===================================================================

generator:
  env: dev
  api-prefix: api
  template-path: ./src/main/java

  test-host: http://localhost

  writers:
    force-suffix: .example

    postman:
      enabled: true
      path: ./src/output
    testcases:
      enabled: true
      path: ./src/output/testcases

    laravel:
      enabled: true
      path: ./src/output/laravel

      bo-suffix: BO
      bo-folder: BOs
      dto-suffix: DTO
      dto-folder: DTOs
      service-suffix: Service
      service-folder: Services
    laravel-doc:
      enabled: true
      path: ./src/output/larecipe
      http-prefix: docs
    laravel-auto-test:
      enabled: true
      path: ./src/output/tests
      force-replace: false
      testcases-path: ./src/output/testcases


    nodejs-client:
      enabled: true
      output: ./src/output/nodejs-client
    java-client:
      enabled: true
      path: ./src/output/java-client
      classpath:

spring:
  thymeleaf:
    mode: TEXT
    suffix: .stub
    encoding: UTF-8
    prefix: classpath:/templates/
